/*
 * Copyright (c) Terl Tech Ltd • 12/05/18 18:55 • goterl.com
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.goterl.lazycode.lazysodium.exceptions.SodiumException;
import com.goterl.lazycode.lazysodium.interfaces.CryptoBox;
import com.goterl.lazycode.lazysodium.interfaces.CryptoSign;
import com.goterl.lazycode.lazysodium.utils.KeyPair;
import junit.framework.TestCase;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

/**
 * Tests public and private key encryption.
 */
public class CryptoSignTest extends BaseTest {


    @Test
    public void generateKeyPair() throws SodiumException {
        KeyPair keys = cryptoSignLazy.cryptoSignKeypair();
        assertNotNull(keys);
    }

    @Test
    public void generateDeterministicPublicKeyPair() throws SodiumException {
        byte[] seed = new byte[CryptoSign.SEEDBYTES];
        KeyPair keys = cryptoSignLazy.cryptoSignSeedKeypair(seed);
        KeyPair keys2 = cryptoSignLazy.cryptoSignSeedKeypair(seed);

        TestCase.assertEquals(keys.getPublicKeyString(), keys2.getPublicKeyString());
    }

    @Test
    public void generateDeterministicSecretKeyPair() throws SodiumException {
        byte[] seed = new byte[CryptoSign.SEEDBYTES];
        KeyPair keys = cryptoSignLazy.cryptoSignSeedKeypair(seed);
        KeyPair keys2 = cryptoSignLazy.cryptoSignSeedKeypair(seed);

        TestCase.assertEquals(keys.getSecretKeyString(), keys2.getSecretKeyString());
    }


    @Test
    public void signMessage() throws SodiumException {
        String message = "This should get signed";

        // Generate the client's keypair
        KeyPair clientKeys = cryptoSignLazy.cryptoSignKeypair();

        String signed = cryptoSignLazy.cryptoSign(message, clientKeys.getSecretKeyString());

        // Now we can verify the signed message.
        String resultingMessage = cryptoSignLazy.cryptoSignOpen(signed, clientKeys.getPublicKeyString());

        TestCase.assertNotNull(resultingMessage);
    }




}
