/*
 * Copyright (c) Terl Tech Ltd • 02/05/18 14:09 • goterl.com
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.goterl.lazycode.lazysodium.LazySodium;
import com.goterl.lazycode.lazysodium.Sodium;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class LibraryTest {

    @Test
    public void sodiumLoadsFromResources() {
        try {
            Sodium sodium = Sodium.loadJava();
            LazySodium lazySodium = new LazySodium(sodium);
            assertTrue("Libsodium loads correctly", true);
        } catch (NullPointerException e) {
            assertTrue("Libsodium loads incorrectly", false);

        }
    }


}
