/*
 * Copyright (c) Terl Tech Ltd • 07/05/18 12:05 • goterl.com
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.goterl.lazycode.lazysodium.structs.crypto_secretstream_xchacha20poly1305_state;
import org.junit.Test;

public class SecretStreamTest extends BaseTest {

    @Test
    public void struct() {

        final crypto_secretstream_xchacha20poly1305_state state =
                new crypto_secretstream_xchacha20poly1305_state.ByReference();
        state.k = new byte[8];
        state.pad = new byte[8];
        lazySodium.cryptoSecretStreamXChacha20Poly1305InitPush(state, new byte[8], new byte[8]);

    }




}
